import{createClient}from'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';
const supabase=createClient('https://kxuszpixwfecawdeqkrx.supabase.co','sb_publishable__auyhjNpepXiYdGV5HEJ_A_AGsPbBuS');
const signin=document.querySelector('#signin-panel'),account=document.querySelector('#account-panel'),emailForm=document.querySelector('#email-form'),codeForm=document.querySelector('#code-form'),emailInput=document.querySelector('#email'),codeInput=document.querySelector('#code'),authMessage=document.querySelector('#auth-message'),newsletterMessage=document.querySelector('#newsletter-message'),toggle=document.querySelector('#newsletter-toggle');let pendingEmail='';
function message(el,text,error=false){el.textContent=text;el.className=`message show${error?' error':''}`}
function busy(button,state,label){button.disabled=state;if(label)button.textContent=state?'Please wait…':label}
async function showAccount(session){if(!session){signin.classList.remove('hidden');account.classList.add('hidden');return}signin.classList.add('hidden');account.classList.remove('hidden');document.querySelector('#account-email').textContent=session.user.email;const{data,error}=await supabase.from('customer_profiles').select('marketing_consent').eq('user_id',session.user.id).maybeSingle();if(error){message(newsletterMessage,'We could not load your newsletter setting.',true);return}if(!data){const{error:createError}=await supabase.from('customer_profiles').insert({user_id:session.user.id,email:session.user.email,marketing_consent:false});if(createError)message(newsletterMessage,'Your account is active, but the profile could not be created.',true)}else toggle.checked=Boolean(data.marketing_consent)}
emailForm.addEventListener('submit',async e=>{e.preventDefault();pendingEmail=emailInput.value.trim().toLowerCase();const btn=document.querySelector('#send-code');busy(btn,true,'Send confirmation code');const{error}=await supabase.auth.signInWithOtp({email:pendingEmail,options:{shouldCreateUser:true}});busy(btn,false,'Send confirmation code');if(error){message(authMessage,error.message,true);return}emailForm.classList.add('hidden');codeForm.classList.remove('hidden');message(authMessage,`We sent a six-digit code to ${pendingEmail}. Check your inbox and spam folder.`);codeInput.focus()});
codeForm.addEventListener('submit',async e=>{e.preventDefault();const btn=document.querySelector('#verify-code');busy(btn,true,'Confirm and sign in');const{data,error}=await supabase.auth.verifyOtp({email:pendingEmail,token:codeInput.value.trim(),type:'email'});busy(btn,false,'Confirm and sign in');if(error){message(authMessage,'That code is incorrect or expired. Request a new code and try again.',true);return}await showAccount(data.session)});
document.querySelector('#change-email').addEventListener('click',()=>{codeForm.classList.add('hidden');emailForm.classList.remove('hidden');authMessage.className='message';codeInput.value=''});
toggle.addEventListener('change',async()=>{const{data:{session}}=await supabase.auth.getSession();if(!session)return;toggle.disabled=true;const subscribed=toggle.checked;const{error}=await supabase.from('customer_profiles').upsert({user_id:session.user.id,email:session.user.email,marketing_consent:subscribed,consent_at:subscribed?new Date().toISOString():null,unsubscribed_at:subscribed?null:new Date().toISOString()},{onConflict:'user_id'});toggle.disabled=false;if(error){toggle.checked=!subscribed;message(newsletterMessage,'Could not save your preference. Please try again.',true)}else message(newsletterMessage,subscribed?'You are subscribed. Welcome!':'You have unsubscribed.')});
document.querySelector('#signout').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload()});const{data:{session}}=await supabase.auth.getSession();await showAccount(session);
