import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2.57.4/+esm';
const supabase=createClient('https://kxuszpixwfecawdeqkrx.supabase.co','sb_publishable__auyhjNpepXiYdGV5HEJ_A_AGsPbBuS');
const form=document.querySelector('#project-form'),requestDialog=document.querySelector('#request-dialog'),authDialog=document.querySelector('#auth-dialog'),formStatus=document.querySelector('#form-status'),accountButton=document.querySelector('#account-button'),dashboard=document.querySelector('#dashboard');
let currentUser=null,pendingVerificationEmail='',resendTimer=null;
document.querySelector('#year').textContent=new Date().getFullYear();
function setStatus(e,m,x=false){e.textContent=m;e.classList.toggle('error',x)}
function friendlyAuthError(error){const m=(error?.message||'').toLowerCase();if(m.includes('error sending confirmation email'))return'We could not send the verification code. Please try again in a moment.';if(m.includes('invalid login credentials'))return'The email or password is incorrect.';if(m.includes('email not confirmed'))return'Verify your email before signing in.';if(m.includes('rate limit'))return'Too many attempts. Please wait a minute and try again.';if(m.includes('already registered')||m.includes('already exists'))return'This email already has an account. Sign in or request a new code.';return error?.message||'Something went wrong. Please try again.'}
function emailTypo(email){const v=String(email).trim().toLowerCase();if(v.endsWith('@gmail.con'))return'That email ends in gmail.con. Did you mean gmail.com?';if(v.endsWith('@gamil.com'))return'Did you mean gmail.com?';return''}
function openAuth(tab='signin'){document.querySelector('.auth-tabs').hidden=tab==='verify';document.querySelectorAll('[data-auth-tab]').forEach(b=>{const a=b.dataset.authTab===tab;b.classList.toggle('active',a);b.setAttribute('aria-selected',String(a))});document.querySelector('#signin-form').hidden=tab!=='signin';document.querySelector('#signup-form').hidden=tab!=='signup';document.querySelector('#verify-form').hidden=tab!=='verify';if(!authDialog.open)authDialog.showModal()}
function showVerification(email){pendingVerificationEmail=email;document.querySelector('#verification-email').textContent=email;document.querySelector('#verification-code').value='';openAuth('verify');setTimeout(()=>document.querySelector('#verification-code').focus(),50)}
function startResendCooldown(){const b=document.querySelector('#resend-code');let s=60;b.disabled=true;b.textContent=`Send again in ${s}s`;clearInterval(resendTimer);resendTimer=setInterval(()=>{s--;if(s<=0){clearInterval(resendTimer);b.disabled=false;b.textContent='Send a new code'}else b.textContent=`Send again in ${s}s`},1000)}
document.querySelectorAll('[data-auth-tab]').forEach(b=>b.addEventListener('click',()=>openAuth(b.dataset.authTab)));accountButton.addEventListener('click',()=>currentUser?dashboard.scrollIntoView({behavior:'smooth'}):openAuth('signin'));document.querySelector('.auth-close').addEventListener('click',()=>authDialog.close());document.querySelector('#request-dialog .close').addEventListener('click',()=>requestDialog.close());
document.querySelector('#signup-form').addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget),s=e.currentTarget.querySelector('.auth-status'),email=String(d.get('email')).trim(),typo=emailTypo(email);if(typo){setStatus(s,typo,true);e.currentTarget.elements.email.focus();return}setStatus(s,'Creating your account and sending a code…');const b=e.currentTarget.querySelector('[type="submit"]');b.disabled=true;const{data:r,error}=await supabase.auth.signUp({email,password:d.get('password'),options:{emailRedirectTo:location.origin,data:{full_name:d.get('fullName'),username:d.get('username')}}});b.disabled=false;if(error){setStatus(s,friendlyAuthError(error),true);return}if(r.session){await ensureProfile(r.user);setStatus(s,'Account created. You are signed in.');setTimeout(()=>authDialog.close(),700)}else{showVerification(email);startResendCooldown()}});
document.querySelector('#verify-form').addEventListener('submit',async e=>{e.preventDefault();const token=String(new FormData(e.currentTarget).get('token')).replace(/\D/g,''),s=e.currentTarget.querySelector('.auth-status');if(token.length!==8){setStatus(s,'Enter the complete 8-digit code.',true);return}const b=e.currentTarget.querySelector('[type="submit"]');b.disabled=true;setStatus(s,'Verifying your code…');const{data,error}=await supabase.auth.verifyOtp({email:pendingVerificationEmail,token,type:'email'});b.disabled=false;if(error){setStatus(s,friendlyAuthError(error),true);return}await ensureProfile(data.user);setStatus(s,'Email verified. Your account is ready.');setTimeout(()=>authDialog.close(),800)});
document.querySelector('#resend-code').addEventListener('click',async e=>{const s=document.querySelector('#verify-form .auth-status');e.currentTarget.disabled=true;setStatus(s,'Sending a new code…');const{error}=await supabase.auth.resend({type:'signup',email:pendingVerificationEmail,options:{emailRedirectTo:location.origin}});if(error){e.currentTarget.disabled=false;setStatus(s,friendlyAuthError(error),true);return}setStatus(s,'A new verification code has been sent.');startResendCooldown()});document.querySelector('#change-email').addEventListener('click',()=>openAuth('signup'));document.querySelector('#verification-code').addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,8)});
document.querySelector('#signin-form').addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(e.currentTarget),s=e.currentTarget.querySelector('.auth-status');setStatus(s,'Signing you in…');const{error}=await supabase.auth.signInWithPassword({email:d.get('email'),password:d.get('password')});if(error){setStatus(s,friendlyAuthError(error),true);return}setStatus(s,'Signed in successfully.');setTimeout(()=>authDialog.close(),500)});document.querySelector('#signout-button').addEventListener('click',async()=>{await supabase.auth.signOut();dashboard.hidden=true;location.hash='top'});
async function ensureProfile(user){if(!user)return;const m=user.user_metadata||{};await supabase.from('customer_profiles').upsert({user_id:user.id,email:user.email,full_name:m.full_name||null,username:m.username||null,updated_at:new Date().toISOString()},{onConflict:'user_id'})}
async function loadRequests(){if(!currentUser)return;const{data,error}=await supabase.from('website_requests').select('id,business_name,website_type,main_goal,budget,status,created_at').order('created_at',{ascending:false}),list=document.querySelector('#request-list');if(error){list.innerHTML='<p class="empty-state">Your requests are temporarily unavailable. Please try again.</p>';return}if(!data.length){list.innerHTML='<p class="empty-state">You have not submitted a website request yet.</p>';return}list.replaceChildren(...data.map(item=>{const a=document.createElement('article');a.className='request-item';const c=document.createElement('div'),t=document.createElement('h3'),d=document.createElement('p'),date=document.createElement('p'),s=document.createElement('span');t.textContent=item.business_name;d.textContent=`${item.website_type} · ${item.main_goal} · ${item.budget}`;date.textContent=new Date(item.created_at).toLocaleDateString();s.className='status-pill';s.textContent=item.status.replace('_',' ');c.append(t,d,date);a.append(c,s);return a}))}
async function updateAccount(session){currentUser=session?.user||null;accountButton.textContent=currentUser?'My account':'Sign in';dashboard.hidden=!currentUser;if(currentUser){await ensureProfile(currentUser);const m=currentUser.user_metadata||{},summary=document.querySelector('#profile-summary');summary.replaceChildren();const n=document.createElement('strong'),email=document.createElement('span');n.textContent=m.full_name||m.username||'Customer account';email.textContent=currentUser.email;summary.append(n,email);await loadRequests()}}
form.addEventListener('submit',async e=>{e.preventDefault();if(!currentUser){setStatus(formStatus,'Sign in or create an account before saving your request.',true);openAuth('signup');return}const d=new FormData(form),r={user_id:currentUser.id,business_name:d.get('business'),website_type:d.get('siteType'),main_goal:d.get('goal'),budget:d.get('budget'),details:d.get('details')||null};setStatus(formStatus,'Saving your request…');const{error}=await supabase.from('website_requests').insert(r);if(error){setStatus(formStatus,'We could not save your request. Please try again.',true);return}setStatus(formStatus,'Your request has been saved successfully.');const msg=`Hello Tivalsdeveloper, I submitted a website request for ${r.business_name}. Please contact me with the next steps.`;document.querySelector('#request-preview').textContent=msg;document.querySelector('#send-whatsapp').href=`https://wa.me/27687345616?text=${encodeURIComponent(msg)}`;document.querySelector('#send-email').href=`mailto:tivalsdeveloper@gmail.com?subject=${encodeURIComponent('Website request — '+r.business_name)}&body=${encodeURIComponent(msg)}`;form.reset();await loadRequests();requestDialog.showModal()});requestDialog.addEventListener('click',e=>{if(e.target===requestDialog)requestDialog.close()});authDialog.addEventListener('click',e=>{if(e.target===authDialog)authDialog.close()});supabase.auth.onAuthStateChange((_e,s)=>setTimeout(()=>updateAccount(s),0));const{data:{session}}=await supabase.auth.getSession();await updateAccount(session);